[2025-05-11T06:51:17.089+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: heart_attack_full_pipeline.branch_for_eda manual__2025-05-11T06:50:59.300806+00:00 [queued]>
[2025-05-11T06:51:17.094+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: heart_attack_full_pipeline.branch_for_eda manual__2025-05-11T06:50:59.300806+00:00 [queued]>
[2025-05-11T06:51:17.094+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-11T06:51:17.101+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): branch_for_eda> on 2025-05-11 06:50:59.300806+00:00
[2025-05-11T06:51:17.108+0000] {standard_task_runner.py:60} INFO - Started process 1683 to run task
[2025-05-11T06:51:17.113+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'heart_attack_full_pipeline', 'branch_for_eda', 'manual__2025-05-11T06:50:59.300806+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/heart_attack_full_pipeline.py', '--cfg-path', '/tmp/tmpfdnv07d7']
[2025-05-11T06:51:17.116+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask branch_for_eda
[2025-05-11T06:51:17.134+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-11T06:51:17.169+0000] {task_command.py:423} INFO - Running <TaskInstance: heart_attack_full_pipeline.branch_for_eda manual__2025-05-11T06:50:59.300806+00:00 [running]> on host c899e1aeab70
[2025-05-11T06:51:17.234+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='posinarevanth@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='heart_attack_full_pipeline' AIRFLOW_CTX_TASK_ID='branch_for_eda' AIRFLOW_CTX_EXECUTION_DATE='2025-05-11T06:50:59.300806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-11T06:50:59.300806+00:00'
[2025-05-11T06:51:17.236+0000] {python.py:201} INFO - Done. Returned value was: eda_process_data
[2025-05-11T06:51:17.236+0000] {branch.py:35} INFO - Branch into eda_process_data
[2025-05-11T06:51:17.237+0000] {skipmixin.py:178} INFO - Following branch eda_process_data
[2025-05-11T06:51:17.256+0000] {skipmixin.py:244} INFO - Skipping tasks [('wait_for_raw', -1)]
[2025-05-11T06:51:17.300+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=heart_attack_full_pipeline, task_id=branch_for_eda, execution_date=20250511T065059, start_date=20250511T065117, end_date=20250511T065117
[2025-05-11T06:51:17.327+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-11T06:51:17.349+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
